import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import imageLoader from '../imageLoader'
import styles from '../styles/Home.module.css'
import { Character, GetCharacterResults } from '../types'
import { SimpleGrid, Stack, Text } from '@chakra-ui/react'

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (
    <Stack className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <hr />
      <SimpleGrid columns={3} spacing={5}>
        {characters.map((character) => {
          return (
            <Stack key={character.id}>
              <Link href={`/characters/${character.id}`}>
                <a>
                  <Text fontSize="xs">{character.name}</Text>
                </a>
              </Link>
              <Image
                loader={imageLoader}
                unoptimized
                src={character.image}
                alt={character.name}
                width="200"
                height="200"
              />
            </Stack>
          )
        })}
      </SimpleGrid>
    </Stack>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch('https://rickandmortyapi.com/api/character')

  const { results }: GetCharacterResults = await res.json()

  return {
    props: {
      characters: results,
    },
  }
}

export default Home
